import pygame.font

WIN_HEIGHT = 500
WIN_WIDTH = 1000

FPS = 60

WHITE = (255, 255, 255)
BLACK = (10, 10, 10)

FONT_NAME = 'calibri'
START_MESSAGE_1 = "Welcome to your journal, are you ready to enter your actions for the day?"
START_MESSAGE_2 = "Press Enter to start!"
START_FONT_SIZE = int(0.025 * WIN_WIDTH)
START_COLOR = WHITE
START1_LOCATION = (WIN_WIDTH+50, (WIN_HEIGHT-50)//2)
START2_LOCATION = (WIN_WIDTH+50, (WIN_HEIGHT+50)//2)


QUESTION_1 = 1
QUESTION_2 = 2
QUESTION_3 = 3
QUESTION_4 = 4
QUESTION_5 = 5
QUESTION_6 = 6
QUESTION_7 = 7
QUESTION_8 = 8
QUESTION_NUM_LIST = [QUESTION_1, QUESTION_2, QUESTION_3, QUESTION_4, QUESTION_5, QUESTION_6, QUESTION_7, QUESTION_8]
